"""create shop data tables

Revision ID: ffe7d602454b
Revises: d0d6a541a12b
Create Date: 2026-09-27 01:13:27.573075
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ffe7d602454b'
down_revision: Union[str, None] = 'd0d6a541a12b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('customer_type', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.shop_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('shop_id', 'customer_id', name='uq_customers_shop_customer')
    )
    op.create_index('ix_customers_shop_name', 'customers', ['shop_id', 'name'], unique=False)
    op.create_table('products',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('part_number', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('mrp', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=150), nullable=True),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('short_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('gst_rate IS NULL OR (gst_rate >= 0 AND gst_rate <= 100)', name='ck_products_gst_rate_range'),
    sa.CheckConstraint('mrp >= 0', name='ck_products_mrp_nonnegative'),
    sa.CheckConstraint('purchase_price >= 0', name='ck_products_purchase_price_nonnegative'),
    sa.CheckConstraint('selling_price >= 0', name='ck_products_selling_price_nonnegative'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.shop_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('shop_id', 'part_number', name='uq_products_shop_part_number'),
    sa.UniqueConstraint('shop_id', 'product_id', name='uq_products_shop_product')
    )
    op.create_table('shop_settings',
    sa.Column('setting_id', sa.Uuid(), nullable=False),
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('setting_key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.shop_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('setting_id'),
    sa.UniqueConstraint('shop_id', 'setting_key', name='uq_shop_settings_shop_key')
    )
    op.create_table('suppliers',
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('supplier_type', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('payment_terms', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.shop_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('supplier_id'),
    sa.UniqueConstraint('shop_id', 'supplier_id', name='uq_suppliers_shop_supplier')
    )
    op.create_index('ix_suppliers_shop_name', 'suppliers', ['shop_id', 'name'], unique=False)
    op.create_table('purchases',
    sa.Column('purchase_id', sa.Uuid(), nullable=False),
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('taxable_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gst_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'received', 'void')", name='ck_purchases_status'),
    sa.CheckConstraint('discount_amount >= 0', name='ck_purchases_discount_nonnegative'),
    sa.CheckConstraint('gst_amount >= 0', name='ck_purchases_gst_nonnegative'),
    sa.CheckConstraint('subtotal >= 0', name='ck_purchases_subtotal_nonnegative'),
    sa.CheckConstraint('taxable_amount >= 0', name='ck_purchases_taxable_nonnegative'),
    sa.CheckConstraint('total_amount >= 0', name='ck_purchases_total_nonnegative'),
    sa.ForeignKeyConstraint(['shop_id', 'supplier_id'], ['suppliers.shop_id', 'suppliers.supplier_id'], name='fk_purchases_shop_supplier', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.shop_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('purchase_id'),
    sa.UniqueConstraint('shop_id', 'purchase_id', name='uq_purchases_shop_purchase'),
    sa.UniqueConstraint('shop_id', 'supplier_id', 'invoice_number', name='uq_purchases_shop_supplier_invoice')
    )
    op.create_index('ix_purchases_shop_purchase_date', 'purchases', ['shop_id', 'purchase_date'], unique=False)
    op.create_index('ix_purchases_shop_supplier', 'purchases', ['shop_id', 'supplier_id'], unique=False)
    op.create_table('sales',
    sa.Column('sale_id', sa.Uuid(), nullable=False),
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('taxable_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gst_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'completed', 'void')", name='ck_sales_status'),
    sa.CheckConstraint('discount_amount >= 0', name='ck_sales_discount_nonnegative'),
    sa.CheckConstraint('gst_amount >= 0', name='ck_sales_gst_nonnegative'),
    sa.CheckConstraint('subtotal >= 0', name='ck_sales_subtotal_nonnegative'),
    sa.CheckConstraint('taxable_amount >= 0', name='ck_sales_taxable_nonnegative'),
    sa.CheckConstraint('total_amount >= 0', name='ck_sales_total_nonnegative'),
    sa.ForeignKeyConstraint(['shop_id', 'customer_id'], ['customers.shop_id', 'customers.customer_id'], name='fk_sales_shop_customer', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.shop_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('sale_id'),
    sa.UniqueConstraint('shop_id', 'invoice_number', name='uq_sales_shop_invoice'),
    sa.UniqueConstraint('shop_id', 'sale_id', name='uq_sales_shop_sale')
    )
    op.create_index('ix_sales_shop_customer', 'sales', ['shop_id', 'customer_id'], unique=False)
    op.create_index('ix_sales_shop_sale_date', 'sales', ['shop_id', 'sale_date'], unique=False)
    op.create_table('payments',
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('sale_id', sa.Uuid(), nullable=True),
    sa.Column('purchase_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='recorded', nullable=False),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status <> 'void' OR void_reason IS NOT NULL", name='ck_payments_void_reason_required'),
    sa.CheckConstraint("status IN ('recorded', 'void')", name='ck_payments_status'),
    sa.CheckConstraint('(sale_id IS NOT NULL AND purchase_id IS NULL) OR (sale_id IS NULL AND purchase_id IS NOT NULL)', name='ck_payments_exactly_one_transaction'),
    sa.CheckConstraint('amount > 0', name='ck_payments_amount_positive'),
    sa.ForeignKeyConstraint(['shop_id', 'purchase_id'], ['purchases.shop_id', 'purchases.purchase_id'], name='fk_payments_shop_purchase', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shop_id', 'sale_id'], ['sales.shop_id', 'sales.sale_id'], name='fk_payments_shop_sale', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.shop_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_index('ix_payments_shop_date', 'payments', ['shop_id', 'payment_date'], unique=False)
    op.create_index('ix_payments_shop_purchase', 'payments', ['shop_id', 'purchase_id'], unique=False)
    op.create_index('ix_payments_shop_sale', 'payments', ['shop_id', 'sale_id'], unique=False)
    op.create_table('purchase_items',
    sa.Column('purchase_item_id', sa.Uuid(), nullable=False),
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('purchase_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('part_number', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('gst_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('discount_amount >= 0', name='ck_purchase_items_discount_nonnegative'),
    sa.CheckConstraint('gst_amount >= 0', name='ck_purchase_items_gst_nonnegative'),
    sa.CheckConstraint('gst_rate >= 0 AND gst_rate <= 100', name='ck_purchase_items_gst_rate_range'),
    sa.CheckConstraint('quantity > 0', name='ck_purchase_items_quantity_positive'),
    sa.CheckConstraint('unit_price >= 0', name='ck_purchase_items_unit_price_nonnegative'),
    sa.ForeignKeyConstraint(['shop_id', 'product_id'], ['products.shop_id', 'products.product_id'], name='fk_purchase_items_shop_product', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shop_id', 'purchase_id'], ['purchases.shop_id', 'purchases.purchase_id'], name='fk_purchase_items_shop_purchase', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('purchase_item_id'),
    sa.UniqueConstraint('shop_id', 'product_id', 'purchase_item_id', name='uq_purchase_items_shop_product_purchase_item'),
    sa.UniqueConstraint('shop_id', 'purchase_item_id', name='uq_purchase_items_shop_purchase_item')
    )
    op.create_index('ix_purchase_items_shop_product', 'purchase_items', ['shop_id', 'product_id'], unique=False)
    op.create_index('ix_purchase_items_shop_purchase', 'purchase_items', ['shop_id', 'purchase_id'], unique=False)
    op.create_table('sale_items',
    sa.Column('sale_item_id', sa.Uuid(), nullable=False),
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('sale_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('part_number', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('gst_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('discount_amount >= 0', name='ck_sale_items_discount_nonnegative'),
    sa.CheckConstraint('gst_amount >= 0', name='ck_sale_items_gst_nonnegative'),
    sa.CheckConstraint('gst_rate >= 0 AND gst_rate <= 100', name='ck_sale_items_gst_rate_range'),
    sa.CheckConstraint('quantity > 0', name='ck_sale_items_quantity_positive'),
    sa.CheckConstraint('unit_price >= 0', name='ck_sale_items_unit_price_nonnegative'),
    sa.ForeignKeyConstraint(['shop_id', 'product_id'], ['products.shop_id', 'products.product_id'], name='fk_sale_items_shop_product', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shop_id', 'sale_id'], ['sales.shop_id', 'sales.sale_id'], name='fk_sale_items_shop_sale', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sale_item_id'),
    sa.UniqueConstraint('shop_id', 'product_id', 'sale_item_id', name='uq_sale_items_shop_product_sale_item'),
    sa.UniqueConstraint('shop_id', 'sale_item_id', name='uq_sale_items_shop_sale_item')
    )
    op.create_index('ix_sale_items_shop_product', 'sale_items', ['shop_id', 'product_id'], unique=False)
    op.create_index('ix_sale_items_shop_sale', 'sale_items', ['shop_id', 'sale_id'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('movement_id', sa.Uuid(), nullable=False),
    sa.Column('shop_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('movement_type', sa.String(length=20), nullable=False),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('sale_item_id', sa.Uuid(), nullable=True),
    sa.Column('purchase_item_id', sa.Uuid(), nullable=True),
    sa.Column('reverses_movement_id', sa.Uuid(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(movement_type = 'opening_stock' AND quantity_delta >= 0 AND sale_item_id IS NULL AND purchase_item_id IS NULL AND reverses_movement_id IS NULL) OR (movement_type = 'purchase' AND quantity_delta > 0 AND purchase_item_id IS NOT NULL AND sale_item_id IS NULL AND reverses_movement_id IS NULL) OR (movement_type = 'sale' AND quantity_delta < 0 AND sale_item_id IS NOT NULL AND purchase_item_id IS NULL AND reverses_movement_id IS NULL) OR (movement_type = 'adjustment' AND quantity_delta <> 0 AND sale_item_id IS NULL AND purchase_item_id IS NULL AND reverses_movement_id IS NULL) OR (movement_type = 'reversal' AND quantity_delta <> 0 AND sale_item_id IS NULL AND purchase_item_id IS NULL AND reverses_movement_id IS NOT NULL)", name='ck_inventory_movements_source'),
    sa.CheckConstraint("movement_type IN ('opening_stock', 'purchase', 'sale', 'adjustment', 'reversal')", name='ck_inventory_movements_type'),
    sa.ForeignKeyConstraint(['shop_id', 'product_id', 'purchase_item_id'], ['purchase_items.shop_id', 'purchase_items.product_id', 'purchase_items.purchase_item_id'], name='fk_inventory_movements_shop_purchase_item', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shop_id', 'product_id', 'reverses_movement_id'], ['inventory_movements.shop_id', 'inventory_movements.product_id', 'inventory_movements.movement_id'], name='fk_inventory_movements_reversal', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shop_id', 'product_id', 'sale_item_id'], ['sale_items.shop_id', 'sale_items.product_id', 'sale_items.sale_item_id'], name='fk_inventory_movements_shop_sale_item', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shop_id', 'product_id'], ['products.shop_id', 'products.product_id'], name='fk_inventory_movements_shop_product', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.shop_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('movement_id'),
    sa.UniqueConstraint('shop_id', 'movement_id', name='uq_inventory_movements_shop_movement'),
    sa.UniqueConstraint('shop_id', 'product_id', 'movement_id', name='uq_inventory_movements_shop_product_movement')
    )
    op.create_index('ix_inventory_movements_shop_product_created', 'inventory_movements', ['shop_id', 'product_id', 'created_at'], unique=False)
    op.create_index('uq_inventory_movements_opening_product', 'inventory_movements', ['shop_id', 'product_id'], unique=True, postgresql_where=sa.text("movement_type = 'opening_stock'"))
    op.create_index('uq_inventory_movements_purchase_item', 'inventory_movements', ['shop_id', 'purchase_item_id'], unique=True, postgresql_where=sa.text('purchase_item_id IS NOT NULL'))
    op.create_index('uq_inventory_movements_reversal', 'inventory_movements', ['shop_id', 'reverses_movement_id'], unique=True, postgresql_where=sa.text('reverses_movement_id IS NOT NULL'))
    op.create_index('uq_inventory_movements_sale_item', 'inventory_movements', ['shop_id', 'sale_item_id'], unique=True, postgresql_where=sa.text('sale_item_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_inventory_movements_sale_item', table_name='inventory_movements', postgresql_where=sa.text('sale_item_id IS NOT NULL'))
    op.drop_index('uq_inventory_movements_reversal', table_name='inventory_movements', postgresql_where=sa.text('reverses_movement_id IS NOT NULL'))
    op.drop_index('uq_inventory_movements_purchase_item', table_name='inventory_movements', postgresql_where=sa.text('purchase_item_id IS NOT NULL'))
    op.drop_index('uq_inventory_movements_opening_product', table_name='inventory_movements', postgresql_where=sa.text("movement_type = 'opening_stock'"))
    op.drop_index('ix_inventory_movements_shop_product_created', table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index('ix_sale_items_shop_sale', table_name='sale_items')
    op.drop_index('ix_sale_items_shop_product', table_name='sale_items')
    op.drop_table('sale_items')
    op.drop_index('ix_purchase_items_shop_purchase', table_name='purchase_items')
    op.drop_index('ix_purchase_items_shop_product', table_name='purchase_items')
    op.drop_table('purchase_items')
    op.drop_index('ix_payments_shop_sale', table_name='payments')
    op.drop_index('ix_payments_shop_purchase', table_name='payments')
    op.drop_index('ix_payments_shop_date', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_sales_shop_sale_date', table_name='sales')
    op.drop_index('ix_sales_shop_customer', table_name='sales')
    op.drop_table('sales')
    op.drop_index('ix_purchases_shop_supplier', table_name='purchases')
    op.drop_index('ix_purchases_shop_purchase_date', table_name='purchases')
    op.drop_table('purchases')
    op.drop_index('ix_suppliers_shop_name', table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_table('shop_settings')
    op.drop_table('products')
    op.drop_index('ix_customers_shop_name', table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
